spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://postgres:5432/notification
    user: admin
    password: admin
    enabled: true
    baseline-on-migrate: true

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: notification
    version: 0.0.1

